# Generated by Django 5.2.5 on 2026-02-07 05:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_alter_orderitem_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique employee identifier', max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('scooter', 'Scooter'), ('car', 'Car'), ('van', 'Van'), ('truck', 'Truck')], max_length=20)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_delivery', 'On Delivery'), ('off_duty', 'Off Duty')], default='available', max_length=20)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Current latitude position', max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Current longitude position', max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('successful_deliveries', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Personnel',
                'verbose_name_plural': 'Delivery Personnel',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('nearby', 'Nearby'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='assigned', max_length=20)),
                ('pickup_latitude', models.DecimalField(decimal_places=6, help_text='Pickup location latitude', max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, help_text='Pickup location longitude', max_digits=9)),
                ('delivery_latitude', models.DecimalField(decimal_places=6, help_text='Delivery destination latitude', max_digits=9)),
                ('delivery_longitude', models.DecimalField(decimal_places=6, help_text='Delivery destination longitude', max_digits=9)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, help_text="Driver's current latitude", max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, help_text="Driver's current longitude", max_digits=9, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('total_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Total distance in kilometers', max_digits=8, null=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('proof_of_delivery_photo', models.ImageField(blank=True, null=True, upload_to='delivery_proofs/')),
                ('customer_signature', models.ImageField(blank=True, null=True, upload_to='delivery_signatures/')),
                ('customer_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('customer_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.deliverypersonnel')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='orders.order')),
            ],
            options={
                'verbose_name': 'Delivery Tracking',
                'verbose_name_plural': 'Delivery Trackings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_status_changes', to=settings.AUTH_USER_MODEL)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='delivery.deliverytracking')),
            ],
            options={
                'verbose_name': 'Delivery Status History',
                'verbose_name_plural': 'Delivery Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, help_text='Speed in km/h', max_digits=5, null=True)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='delivery.deliverytracking')),
            ],
            options={
                'verbose_name': 'Delivery Route Point',
                'verbose_name_plural': 'Delivery Route Points',
                'ordering': ['recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deliverypersonnel',
            index=models.Index(fields=['employee_id'], name='delivery_de_employe_ed2b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypersonnel',
            index=models.Index(fields=['status'], name='delivery_de_status_23902e_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverytracking',
            index=models.Index(fields=['order'], name='delivery_de_order_i_67b594_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverytracking',
            index=models.Index(fields=['driver'], name='delivery_de_driver__b253b0_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverytracking',
            index=models.Index(fields=['status'], name='delivery_de_status_c57560_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverytracking',
            index=models.Index(fields=['created_at'], name='delivery_de_created_f7f26e_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverystatushistory',
            index=models.Index(fields=['tracking', 'timestamp'], name='delivery_de_trackin_28999c_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryroute',
            index=models.Index(fields=['tracking', 'recorded_at'], name='delivery_de_trackin_0d1836_idx'),
        ),
    ]
