# Generated by Django 5.2.5 on 2025-08-23 02:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(help_text='Unique product identifier', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit', models.CharField(help_text='e.g., kg, lb, piece, pack', max_length=50)),
                ('min_order_quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('in_stock', models.BooleanField(default=True)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('origin', models.CharField(blank=True, help_text='Country of origin', max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in grams', max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['item_code'], name='products_pr_item_co_45fc9f_idx'), models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'), models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx')],
            },
        ),
    ]
